name: Build Gradle Project

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-gradle-project:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt-openj9'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run build
        run: ./gradlew build
